name: Frontend CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci_cd_common:
    uses: sdevops5427/reusable-github-actions/.github/workflows/ci.yml@main
    with:
      component: frontend
      appType: nginx